### PR TITLE
Add support for async functions in custom APIs

### PR DESCRIPTION
**Pull request by danderson00**

### CODE REVIEW

**Comment by danderson00** [comment]
@sdsanders This builds on your PR and only runs the test if the current node runtime version is 7 or greater. I also updated the node version that travis uses so the test runs there as well.

Thanks for the contribution!

**Comment by sdsanders** [comment]
@danderson00 thank you sir!

**Comment by danderson00** [comment]
Resolves #529

**Comment by danderson00** [comment]
We'll be releasing the next minor version later this week. Watch this space!

**Comment by sdsanders** [comment]
@danderson00 any news on this release?

**Comment by sdsanders** [comment]
@danderson00 sorry to bug you but any updates on releasing this? Would love to use it in production.

**Pull request merged**
