### PR TITLE
added and example about how to query data

### PR DESCRIPTION
**Pull request by ccasbre27**
We are using mssql and SQL syntax

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ccasbre27__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by adrianhall** [comment]
Hi @ccasbre27 - we are trying to limit what goes into the README.md - there is a sample in the samples directory.  Feel free to update the sample if you don't feel it meets the requirement.

**Comment by ccasbre27** [comment]
Ok sorry, now that I analyse I think that It looks better in the samples/custom-api-sql-stmt , what do you think? Can I contribute on that Readme?

**Comment by adrianhall** [comment]
Yes - please contribute to the samples instead.

**Comment by ccasbre27** [comment]
ok thanks and sorry for the inconvenient

**Pull request closed without merging**
