### PR TITLE
Add way to use custom data providers passed in configuration object

### PR DESCRIPTION
**Pull request by fduch2k**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@fduch2k__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by danderson00** [comment]
Happy to merge this, it was on the list of things to do to support custom data providers. Out of curiosity, are you implementing a data provider?

**Comment by fduch2k** [comment]
Yes, I'm implementing data provider for mongodb. Maybe later will implement data driver for [Sequelize](https://github.com/sequelize/sequelize/)

**Comment by danderson00** [comment]
At some point soon, we will produce some documentation on producing data providers, i.e. API interface, structure of returned results and error behavior. If you need help with any of this, please feel free to drop us a line.

**Pull request merged**
