### PR TITLE
Fixed connection issue

### PR DESCRIPTION
**Pull request by danderson00**

### CODE REVIEW

**Comment by danderson00** [comment]
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/174

**Comment by mamaso** [comment]
Looks good, was playing around with this myself & ran into the error in #174. We could consider catching connection errors immediately after the connect call and logging a failure message in order to resolve #176 (although I feel like these errors will already be logged..)

**Comment by danderson00** [comment]
Will add some commits to address https://github.com/Azure/azure-mobile-apps-node/issues/176

**Comment by danderson00** [comment]
This was unexpected behavior from Promises...

    var reject,
        promise = new Promise(function (res, rej) {
            reject = rej
        })

    promise.catch(function () {
        throw 'gfdgdf'
    })

    reject()

The thrown exception does not bubble up as an unhandled exception. This situation requires another catch block after the first. Something to be aware of!

Added some logging to ensure the exception is logged on connection failure.

**Comment by Mimetis** [comment]
Well , you return the close() promise to the caller, not the executeRequest promise, so there is a bug here.
I did the same in my first approach, then I delete the close method. I assume there is no reason to saturate the pool connection in one http request.

**Comment by danderson00** [comment]
Yeh, caused a lot of unit test failures. We can close the connection by changing the code to

     return connection.connect()
            .then(executeRequest)
            .then(function (results) {
                close();
                return results;
            })

But I've left this out for now. I'm unsure of the impact of not closing the connection. I'm assuming connection pooling will handle this, but we may need to monitor for potential performance hits.

**Comment by Mimetis** [comment]
In my opinion the comment is wrong. Like Ado.NET, you should open, execute then close as soon as possible

**Pull request merged**
