### PR TITLE
Per user tables

### PR DESCRIPTION
**Pull request by danderson00**
@paulbatum @fabiocav @mamaso @shrishrirang 

Enabled by adding a perUser: true property to table definitions. userIdColumn can either be specified on table definition or on root configuration object. Default is userId.

We need to make sure this works properly. There will be caveats we need to make clear to the user when they modify operations, but we need to make sure the default configuration is secure. Any more test cases you can think of?

### CODE REVIEW

**Comment by danderson00** [comment]
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/381

**Comment by mamaso** [comment]
looks good, I think the test coverage is solid as well.  It'd be cool to have more rbac stuff but that's far more complex

**Comment by danderson00** [comment]
We'll add some RBAC later, it's on the cards.

**Comment by paulbatum** [comment]
What happens when I turn it on for a table with existing data? I assume the anonymous data sits there, but is never accessible via the API?

From the current implementation, I'm guessing that if I use the tables API to query a per-user table from within a script, no filtering will occur? I am a bit worried that this will surprise customers and lead to unfortunate security bugs in their apps. Thoughts?

**Comment by danderson00** [comment]
The user id column will get created but not populated. The user will need to populate the column manually.

That's correct. This is one of the caveats I was talking about. I agree it will be easy for users to shoot themselves in the foot. We can maybe look at adding a parameter to the exposed CRUD methods that accepts a user object, that might mitigate it slightly.

**Pull request merged**
