### PR TITLE
Fixes for the typings field for typescript / VSCode in package.json

### PR DESCRIPTION
**Pull request by joewood**
Imports the ambient type definitions into a typed module (main.d.ts) and replaces the entry in the package.json file to use this file instead.  Also removes the local dependency on express.d.ts (assumes it has previously been imported by the user).

Relates to #374.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@joewood__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@joewood__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by joewood** [comment]
Yes, I think so (at least in a TypeScript project it works). I haven't tried it in a pure JS project yet.
This works for now, but requires the user to install the Express typings themselves with:
```
tsd init
tsd install express -so
```
The better fix would be to use the new **typings** tool, which lets libraries declare their dependencies.

**Comment by danderson00** [comment]
Thanks @joewood!

**Pull request merged**
